### ISSUE TITLE
Add continuous deployment for different platforms.

### ISSUE THREAD

**Issue by shijiashuai** [Xtra-Computing/thundersvm#176]
## test builds
- [x] CPU build on Ubuntu
- [x] GPU build on Ubuntu
- [x] CPU build on Windows
- [x] CPU build on MacOS

## generate wheels
- [x] GPU wheels with CUDA 8, 9, 10 on linux_amd64
- [x] CPU wheels on linux_amd64
- [x] CPU wheels on Windows
- [x] CPU wheels on MacOS
